agentParam:
  name: agent1
  state_dim: 2
  state_indices: 
    - 1
  control_indices: 
    - 1
  q_mf:
    1: 0.0
  p_l: 
    1: 0.0
  p_mf:
    1: 0.0
  q_mf_dot: 
    1: 0.0
  u_mf: 
    1: 0.0
algParam:
  gamma: 1.0
  Gamma: 1.0
  K: 2
  T: 10
  n_s: 10
odeParam:
  integrateTol: 10**-3
  maxIter: 400
bbValues:
  q_mf:
    1: 0.0
    2: 0.0
  p_l: 
    1: 0.0
    2: 0.0
  p_mf:
    1: 0.0
    2: 0.0
  q_mf_dot: 
    1: 0.0
    2: 0.0
  u_mf: 
    1: 0.0

